[build]
  command = "npm run build"
  publish = "dist"

# Redirige las llamadas a la API al backend en Render
[[redirects]]
  from = "/api/*"
  to = "https://codisec-api.onrender.com/api/:splat"
  status = 200
  force = true

# Redirección para la SPA (Single Page Application)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200